language: node_js
sudo: false
node_js:
  - '4'
  - '6'
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  # Prevent Bower from asking questions.
  - export CI=true
  # Log HTTP requests
  - npm config set loglevel http
install:
  - time npm install
