# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get the Node version with matching major & minor numbers
  - ps: Install-Product node $env:nodejs_version
  # Prevent Bower from asking questions.
  - set CI=true
  # Log HTTP requests.
  - npm config set loglevel http
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off

# Finish immediately if one of the jobs fails. (temporarily disabled)
matrix:
#  fast_finish: true
  allow_failures:
    - nodejs_version: "4"

# Set up cache, clear it on package.json changes.
# NOTE: Cache disabled for now.
#cache:
#  # npm cache.
#  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json
#  # Local npm packages.
#  - node_modules -> package.json

# Set build version format here instead of in the admin panel.
version: "{build}"
